---

- name: All packages needed by apache are installed in their latest version
  action: apt pkg={{ item }} state=latest
  with_items:
    - apache2
  notify:
    - ensure apache
    - restart apache

- name: All needed apache modules are enabled
  action: apache2_module name={{ item }} state=present
  with_items:
    - deflate
    - env
    - expires
    - filter
    - headers
    - mime
    - negotiation
    - php5
    - reqtimeout
    - rewrite
    - setenvif
    - ssl
    - status
    - vhost_alias
  notify:
    - restart apache

- name: A /var/www directory exists
  action: file dest=/var/www state=directory
  notify:
    - restart apache

- name: Default virtual host for apache is not enabled
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart apache

- name: deactivating indexes in apache
  lineinfile: dest="/etc/apache2/apache2.conf"
              regexp='^\tOptions Indexes FollowSymLinks'
              line='\tOptions -Indexes +FollowSymLinks'
  notify:
    - restart apache
