---

- name: Composer is downloaded
  action: command /usr/bin/curl -s http://getcomposer.org/installer -o /tmp/composer_installer

- name: Composer is installed into /usr/bin
  action: command /usr/bin/php /tmp/composer_installer --install-dir=/usr/bin --filename=composer
