---

- name: All packages needed by webtier (imagemagick, memcached and sendmail) are installed in their latest version
  action: apt pkg={{ item }} state=latest
  with_items:
    - imagemagick
    - memcached
    - sendmail
