---

- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded

- name: ensure apache
  service: name=apache2 state=started enabled=true
